FROM itzg/minecraft-server:latest

ENV EULA=TRUE
ENV TYPE=PAPER
ENV VERSION=LATEST
ENV MEMORY=512M
ENV ONLINE_MODE=false
ENV DB_HOST=localhost
ENV DB_PORT=5432
ENV DB_NAME=postgres
ENV DB_USER=postgres
ENV DB_PASS=sicheresPasswort123

COPY plugins/ /plugins/

EXPOSE 25565
